### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rgriebl** [anton-yurchenko/git-release#64] opened 2022-02-20 18:00 UTC
Just wanted to create a new release of my software and this happened:

https://github.com/rgriebl/haiq/runs/5265915927?check_suite_focus=true

**Comment by anton-yurchenko** [comment] 2022-02-20 22:05
Seems like the API has not responded at all this time...

I have added a response validation in [v4.2.3](https://github.com/anton-yurchenko/git-release/releases/tag/v4.2.3), this should force git-release to retry the upload.

There is a chance the API might reply with an unexpected HTTP code in case the asset was partially uploaded. Please reopen this issue if that happens or the issue is reoccurring.

**Comment by rgriebl** [comment] 2022-02-20 22:58
Thanks for the quick fix, but I just retried and got the same result (although with a different asset this time).

https://github.com/rgriebl/haiq/runs/5267149159?check_suite_focus=true

**Comment by rgriebl** [comment] 2022-02-20 23:00
(BTW: I can't re-open the myself bug, since you as the repo owner closed it)

**Comment by rgriebl** [comment] 2022-02-21 12:08
Thanks again for the fix, but of course it just worked now ...

https://github.com/rgriebl/haiq/runs/5273777573?check_suite_focus=true

I'll keep this mind though and will check the logs whenever I do a release.

**Comment by anton-yurchenko** [comment] 2022-03-13 17:12
I was able to catch a network issue and `git-release` recovery:

```
DEBUG git-release v4.2.4
INFO creating v1.0.0 release
INFO release created successfully 🎉
INFO uploading asset                               asset=<asset>
WARNING error uploading asset: Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": unexpected EOF  asset=<asset>
WARNING Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": unexpected EOF  asset=<asset>
INFO retrying (2/4) uploading asset in 9 seconds   asset=<asset>
WARNING error uploading asset: Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": write tcp 172.17.0.2:56716->140.82.114.13:443: write: connection reset by peer  asset=<asset>
WARNING Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": write tcp 172.17.0.2:56716->140.82.114.13:443: write: connection reset by peer  asset=<asset>
INFO retrying (3/4) uploading asset in 27 seconds  asset=<asset>
INFO assets uploaded successfully 🎉
```

In addition to that, here is a failure from which `git-release` was unable to recover. It was a long downtime of GitHub API:

```
DEBUG git-release v4.2.4
INFO creating v2.0.0 release
INFO release created successfully 🎉
INFO uploading asset                               asset=<asset>
WARNING error uploading asset: Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": write tcp 172.17.0.2:55104->140.82.114.13:443: write: connection reset by peer  asset=<asset>
WARNING Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": write tcp 172.17.0.2:55104->140.82.114.13:443: write: connection reset by peer  asset=<asset>
INFO retrying (2/4) uploading asset in 9 seconds   asset=<asset>
WARNING error uploading asset: Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": read tcp 172.17.0.2:55126->140.82.114.13:443: read: connection reset by peer  asset=<asset>
WARNING Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": read tcp 172.17.0.2:55126->140.82.114.13:443: read: connection reset by peer  asset=<asset>
INFO retrying (3/4) uploading asset in 27 seconds  asset=<asset>
WARNING error uploading asset: Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": write tcp 172.17.0.2:37556->140.82.113.13:443: write: connection reset by peer  asset=<asset>
WARNING Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": write tcp 172.17.0.2:37556->140.82.113.13:443: write: connection reset by peer  asset=<asset>
INFO retrying (4/4) uploading asset in 81 seconds  asset=<asset>
WARNING error uploading asset: Post "https://uploads.github.com/repos/<organization>/<repository>/releases/<id>/assets?name=<asset>": write tcp 172.17.0.2:46948->140.82.114.14:443: write: connection reset by peer  asset=<asset>
ERROR maximum attempts reached uploading asset: <asset> 
FATAL error uploading assets
```

Not sure there is a reason to add more attempts, as this will surely increase the billing by occupying the runner longer. Especially as such occasions are not transient network interrupts but API downtimes that usually require more than a couple of minutes to be fixed.

*Closing this issue*

**Closed by anton-yurchenko** 2022-03-13 17:12 UTC
Labels: bug, v4
